### ISSUE TITLE
Publish to Open VSIX

### ISSUE THREAD

**Issue by silopolis** [wottpal/vscode-auto-open-workspace#2]
Hi,

First, thanks a ton for this extension that's the perfect GitHub Desktop companion while desktop/desktop#7007 is not fixed!

Then, a "small" request as the subject implies, for us poor VSCodium users :)

Thank you again for sharing your work
Take care
J

**Comment by wottpal** [comment]
Thanks for the positive feedback.

https://open-vsx.org/extension/zoma/vscode-auto-open-workspace

🫡

**Comment by silopolis** [comment]
Man, that was faaast!

Thanks for caring
Have a nice weekend :)
